# Generated by Django 4.2.7 on 2023-12-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sub',
            new_name='subject',
        ),
    ]
